// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2021-12-09 16:58:32.755954 +0800 CST m=+0.026151247

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/Zrealshadow/bitCask-kv",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/db/:dbname": {
            "get": {
                "description": "Get Key - Value in DB",
                "produces": [
                    "application/json"
                ],
                "summary": "Get Key - Value in DB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "block name",
                        "name": "dbname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Get key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "err_code：10000001 参数错误\"；",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "err_code：10000000 服务错误 err_code: 10000002 无数据\"；",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Put Key - Value in DB",
                "produces": [
                    "application/json"
                ],
                "summary": "Put Key - Value in DB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "block name",
                        "name": "dbname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "put key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "put value",
                        "name": "dbname",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "err_code：10000001 参数错误\"；",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "err_code：10000000 服务错误 err_code: 10000002 无数据\"；",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Key - Value in DB",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete Key - Value in DB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "block name",
                        "name": "dbname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Get key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "err_code：10000001 参数错误\"；",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "err_code：10000000 服务错误 err_code: 10000002 无数据\"；",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/dbs": {
            "post": {
                "description": "Create DB Block",
                "produces": [
                    "application/json"
                ],
                "summary": "Create DB Block",
                "parameters": [
                    {
                        "type": "string",
                        "description": "block name",
                        "name": "dbname",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok\" \"成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "err_code：10000001 参数错误\"；",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "基于BitCask的K-V储存系统",
	Description: "基于BitCask K-V储存系统服务端",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
